name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app:latest .
        docker tag my-fastapi-app:latest ghcr.io/${{ github.repository }}/my-fastapi-app:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/my-fastapi-app:latest

    - name: Run Docker container
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        HOST: ${{ secrets.HOST }}
      run: |
        docker run -d -p 8000:8000 --name fastapi-container \
          -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
          -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
          -e HOST=${{ secrets.HOST }} \
          ghcr.io/${{ github.repository }}/my-fastapi-app:latest